import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/landing/landing.component').then(m => m.LandingComponent) },
  { path: 'not-eligible', loadComponent: () => import('./pages/not-dev/not-dev.component').then(m => m.NotDevComponent) },
  { path: 'verify', loadComponent: () => import('./pages/absher/absher.component').then(m => m.AbsherComponent), data: { mode: 'register' } },
  { path: 'sign-in', loadComponent: () => import('./pages/absher/absher.component').then(m => m.AbsherComponent), data: { mode: 'login' } },
  { path: 'onboarding/company-verify', loadComponent: () => import('./pages/company-verify/company-verify.component').then(m => m.CompanyVerifyComponent) },
  { path: 'onboarding/team', loadComponent: () => import('./pages/team-invite/team-invite.component').then(m => m.TeamInviteComponent) },
  { path: 'onboarding/project', loadComponent: () => import('./pages/project-onboard/project-onboard.component').then(m => m.ProjectOnboardComponent) },
  { path: 'onboarding/financing', loadComponent: () => import('./pages/financing-onboard/financing-onboard.component').then(m => m.FinancingOnboardComponent) },
  { path: 'submit-success', loadComponent: () => import('./pages/submit-success/submit-success.component').then(m => m.SubmitSuccessComponent) },
  {
    path: 'dashboard',
    loadComponent: () => import('./pages/dashboard-layout/dashboard-layout.component').then(m => m.DashboardLayoutComponent),
    children: [
      { path: '', loadComponent: () => import('./pages/dashboard-overview/dashboard-overview.component').then(m => m.DashboardOverviewComponent) },
      { path: 'companies', loadComponent: () => import('./pages/companies/companies.component').then(m => m.CompaniesPageComponent) },
      { path: 'company/:id', loadComponent: () => import('./pages/company-detail/company-detail.component').then(m => m.CompanyDetailComponent) },
      { path: 'projects', loadComponent: () => import('./pages/projects/projects.component').then(m => m.ProjectsPageComponent) },
      { path: 'project/:id', loadComponent: () => import('./pages/project-detail/project-detail.component').then(m => m.ProjectDetailComponent) },
      { path: 'teams', loadComponent: () => import('./pages/teams/teams.component').then(m => m.TeamsPageComponent) },
      { path: 'applications', loadComponent: () => import('./pages/applications/applications.component').then(m => m.ApplicationsComponent) },
    ]
  },
  { path: 'project/new', loadComponent: () => import('./pages/add-project/add-project.component').then(m => m.AddProjectComponent) },
  { path: 'application/new', loadComponent: () => import('./pages/add-application/add-application.component').then(m => m.AddApplicationComponent) },
  { path: 'company/new', loadComponent: () => import('./pages/add-company/add-company.component').then(m => m.AddCompanyComponent) },
  { path: 'company/:companyId/credentials', loadComponent: () => import('./pages/edit-credentials/edit-credentials.component').then(m => m.EditCredentialsComponent) },
  { path: 'application/:id/status', loadComponent: () => import('./pages/submitted/submitted.component').then(m => m.SubmittedComponent) },
  { path: 'application/:id/term-sheet', loadComponent: () => import('./pages/offer/offer.component').then(m => m.OfferComponent) },
  { path: 'application/:id/activity', loadComponent: () => import('./pages/activity-log/activity-log.component').then(m => m.ActivityLogComponent) },
  { path: 'application/:id/accepted', loadComponent: () => import('./pages/offer-result/offer-result.component').then(m => m.OfferResultComponent), data: { accepted: true } },
  { path: 'application/:id/declined', loadComponent: () => import('./pages/offer-result/offer-result.component').then(m => m.OfferResultComponent), data: { accepted: false } },
  { path: 'profile', loadComponent: () => import('./pages/profile/profile.component').then(m => m.ProfileComponent) },
  { path: 'support', loadComponent: () => import('./pages/support/support.component').then(m => m.SupportComponent) },
  { path: 'verify/owner/:token', loadComponent: () => import('./pages/owner-verify/owner-verify.component').then(m => m.OwnerVerifyComponent) },
  { path: 'invite/accept', loadComponent: () => import('./pages/invite-accept/invite-accept.component').then(m => m.InviteAcceptComponent) },
  { path: 'design-system', loadComponent: () => import('./pages/design-system/design-system.component').then(m => m.DesignSystemComponent) },
  { path: '**', redirectTo: '' },
];
